config/routes.rb
Rails.application.routes.draw do


  get 'admin' => 'admin#index', as: 'admin_index', via: :all
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :download, :on => :member
    get :who_bought, on: :member
  end
  #get 'store/index'

  resources :products do
    get :download, :on => :member
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sortilegios Chirp </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
        I18n.defaultLocale = "<%= I18n.default_locale %>";
        I18n.locale        = "<%= I18n.locale %>";
    </script>
  </head>

  <body class="<%= controller.controller_name %>">
  <div id="banner">
    <!--When provided, save the locale in the session.-->
    <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale',
                       options_for_select(LANGUAGES, I18n.locale.to_s),
                       onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>


    <%= image_tag 'escudo.png', :size => "64x184", alt: 'Harry Potter' %>
    <h2>SORTILEGIOS CHIRP</h2>
    <span class="title"><%= @page_title %></span>
  </div>
  <div id="columns">
    <div id="side">
<!--referencia del diseño-->
      <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
          <% end %>
      <% end %>

      <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders',   orders_path   %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users',    users_path    %></li>
          </ul>
          <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>



      <!--Hacer orden en la barra lateral-->
      <%= render Order.find(session[:order_id]) if session[:order_id] -%>

      <ul>
        <li><a href="http://www...."><%= t('.home') %></a></li>
        <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
        <li><a href="http://www..../news"><%= t('.news') %></a></li>
        <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
      </ul>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
  </body>
</html>